# Generated by Django 4.1.7 on 2023-03-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userprofile_chatmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='chatMessages',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
