# Generated by Django 4.1.7 on 2023-03-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_topic_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
