# Generated by Django 4.1.7 on 2023-03-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_room_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='avatar',
        ),
    ]
